$(".most-popular__slider").slick({
    arrows: true,
    dots: true,
    adaptiveHeight: false,
    slidesToScroll: 1,
    speed: 1500,
    easing: 'easy', 
    infinite: true, 
    initialSlide: 0,
    autoplay: false,
    autoplaySpeed: 3500,
    pauseOnFocus: true,
    pauseOnHover: true,
    pauseOnDots: true,
    draggable: false, 
    swipe: false, 
    touchThreshold: 10, 
    touchMove: false, 
    waitForAnimate: true,
    variableWidth: true,
});

$(".instructor__slider").slick({
    arrows: true,
    dots: true,
    adaptiveHeight: false,
    slidesToScroll: 1,
    speed: 1500,
    easing: 'easy', 
    infinite: true, 
    initialSlide: 0,
    autoplay: false,
    autoplaySpeed: 3500,
    pauseOnFocus: true,
    pauseOnHover: true,
    pauseOnDots: true,
    draggable: false, 
    swipe: false, 
    touchThreshold: 10, 
    touchMove: false, 
    waitForAnimate: true,
    variableWidth: true,
});

$(".feedback__slider").slick({
    arrows: true,
    dots: true,
    adaptiveHeight: false,
    slidesToShow: 2,
    slidesToScroll: 1,
    speed: 1500,
    easing: 'easy', 
    infinite: true, 
    initialSlide: 0,
    autoplay: false,
    autoplaySpeed: 3500,
    pauseOnFocus: true,
    pauseOnHover: true,
    pauseOnDots: true,
    draggable: false, 
    swipe: false, 
    touchThreshold: 10, 
    touchMove: false, 
    waitForAnimate: true,
    variableWidth: true,
});

